---
- name: yum module
  hosts: all
  become: true
  tasks:
    - name: yum update all 
      yum:
        name: '*'
        state: latest
        update_cache: yes
    - name: reboot server
      reboot:
        msg: "reboot by ansible"
        pre_reboot_delay: 5
        post_reboot_delay: 10
        test_command: "whoami"
