---
- name: installation of httpd and apache
  hosts: all
  become: yes
  tasks:
    - name: install httpd server
      yum:
        name: httpd
        state: present
      when: ansible_facts['os_family']|lower == 'redhat'
    - name: start & enable service
      service:
        name: httpd
        state: started
      when: ansible_facts['os_family']|lower == 'redhat'

    - name: install httpd server
      yum:
        name: apache2
        state: present
      when: ansible_facts['os_family']|lower == 'debian'
    - name: start & enable service
      service:
        name: apache2
        state: started
      when: ansible_facts['os_family']|lower == 'debian'

    - name: copy index html file
      copy:
        src: index.html
        dest: /var/www/html/index.html
        mode: 0755
        owner: root
        group: root
