---
- name: install httpd & restart service
  hosts: all
  become: true
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present
    - name: restrat and enable service
      service:
        name: httpd
        state: restarted
        enabled: true
